/* Auto-generated by genmsg_cpp for file /home/linaro/fearing_rosbuild_overlay/asrl_comms/asrl_sensor_msgs/msg/Packet.msg */
#ifndef ASRL_SENSOR_MSGS_MESSAGE_PACKET_H
#define ASRL_SENSOR_MSGS_MESSAGE_PACKET_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "asrl_sensor_msgs/IpAddress.h"
#include "asrl_sensor_msgs/IpAddress.h"

namespace asrl_sensor_msgs
{
template <class ContainerAllocator>
struct Packet_ {
  typedef Packet_<ContainerAllocator> Type;

  Packet_()
  : source()
  , sourcePort(0)
  , seqNumber(0)
  , destination()
  , destinationPort(0)
  , data()
  {
  }

  Packet_(const ContainerAllocator& _alloc)
  : source(_alloc)
  , sourcePort(0)
  , seqNumber(0)
  , destination(_alloc)
  , destinationPort(0)
  , data(_alloc)
  {
  }

  typedef  ::asrl_sensor_msgs::IpAddress_<ContainerAllocator>  _source_type;
   ::asrl_sensor_msgs::IpAddress_<ContainerAllocator>  source;

  typedef uint16_t _sourcePort_type;
  uint16_t sourcePort;

  typedef uint64_t _seqNumber_type;
  uint64_t seqNumber;

  typedef  ::asrl_sensor_msgs::IpAddress_<ContainerAllocator>  _destination_type;
   ::asrl_sensor_msgs::IpAddress_<ContainerAllocator>  destination;

  typedef uint16_t _destinationPort_type;
  uint16_t destinationPort;

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  data;


  typedef boost::shared_ptr< ::asrl_sensor_msgs::Packet_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asrl_sensor_msgs::Packet_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Packet
typedef  ::asrl_sensor_msgs::Packet_<std::allocator<void> > Packet;

typedef boost::shared_ptr< ::asrl_sensor_msgs::Packet> PacketPtr;
typedef boost::shared_ptr< ::asrl_sensor_msgs::Packet const> PacketConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::asrl_sensor_msgs::Packet_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::asrl_sensor_msgs::Packet_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace asrl_sensor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::asrl_sensor_msgs::Packet_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::asrl_sensor_msgs::Packet_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::asrl_sensor_msgs::Packet_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1c0f9f8290390c9313fb27fb31c8e9bd";
  }

  static const char* value(const  ::asrl_sensor_msgs::Packet_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1c0f9f8290390c93ULL;
  static const uint64_t static_value2 = 0x13fb27fb31c8e9bdULL;
};

template<class ContainerAllocator>
struct DataType< ::asrl_sensor_msgs::Packet_<ContainerAllocator> > {
  static const char* value() 
  {
    return "asrl_sensor_msgs/Packet";
  }

  static const char* value(const  ::asrl_sensor_msgs::Packet_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::asrl_sensor_msgs::Packet_<ContainerAllocator> > {
  static const char* value() 
  {
    return "IpAddress source\n\
uint16 sourcePort\n\
\n\
uint64 seqNumber\n\
\n\
IpAddress destination\n\
uint16 destinationPort\n\
\n\
uint8[] data\n\
================================================================================\n\
MSG: asrl_sensor_msgs/IpAddress\n\
# The 4-byte IPv4 address\n\
uint8[4] address\n\
";
  }

  static const char* value(const  ::asrl_sensor_msgs::Packet_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::asrl_sensor_msgs::Packet_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.source);
    stream.next(m.sourcePort);
    stream.next(m.seqNumber);
    stream.next(m.destination);
    stream.next(m.destinationPort);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Packet_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asrl_sensor_msgs::Packet_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::asrl_sensor_msgs::Packet_<ContainerAllocator> & v) 
  {
    s << indent << "source: ";
s << std::endl;
    Printer< ::asrl_sensor_msgs::IpAddress_<ContainerAllocator> >::stream(s, indent + "  ", v.source);
    s << indent << "sourcePort: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.sourcePort);
    s << indent << "seqNumber: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.seqNumber);
    s << indent << "destination: ";
s << std::endl;
    Printer< ::asrl_sensor_msgs::IpAddress_<ContainerAllocator> >::stream(s, indent + "  ", v.destination);
    s << indent << "destinationPort: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.destinationPort);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASRL_SENSOR_MSGS_MESSAGE_PACKET_H

