/* Auto-generated by genmsg_cpp for file /home/linaro/fearing_rosbuild_overlay/asrl_comms/asrl_sensor_msgs/msg/SerialData.msg */
#ifndef ASRL_SENSOR_MSGS_MESSAGE_SERIALDATA_H
#define ASRL_SENSOR_MSGS_MESSAGE_SERIALDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace asrl_sensor_msgs
{
template <class ContainerAllocator>
struct SerialData_ {
  typedef SerialData_<ContainerAllocator> Type;

  SerialData_()
  : stamp()
  , data()
  {
  }

  SerialData_(const ContainerAllocator& _alloc)
  : stamp()
  , data(_alloc)
  {
  }

  typedef ros::Time _stamp_type;
  ros::Time stamp;

  typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  data;


  typedef boost::shared_ptr< ::asrl_sensor_msgs::SerialData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asrl_sensor_msgs::SerialData_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct SerialData
typedef  ::asrl_sensor_msgs::SerialData_<std::allocator<void> > SerialData;

typedef boost::shared_ptr< ::asrl_sensor_msgs::SerialData> SerialDataPtr;
typedef boost::shared_ptr< ::asrl_sensor_msgs::SerialData const> SerialDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::asrl_sensor_msgs::SerialData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::asrl_sensor_msgs::SerialData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace asrl_sensor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::asrl_sensor_msgs::SerialData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::asrl_sensor_msgs::SerialData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::asrl_sensor_msgs::SerialData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "30d6e0c1226a788b1f0f869ab72b4074";
  }

  static const char* value(const  ::asrl_sensor_msgs::SerialData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x30d6e0c1226a788bULL;
  static const uint64_t static_value2 = 0x1f0f869ab72b4074ULL;
};

template<class ContainerAllocator>
struct DataType< ::asrl_sensor_msgs::SerialData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "asrl_sensor_msgs/SerialData";
  }

  static const char* value(const  ::asrl_sensor_msgs::SerialData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::asrl_sensor_msgs::SerialData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Timestamp\n\
time stamp\n\
\n\
# Serial data\n\
uint8[] data\n\
";
  }

  static const char* value(const  ::asrl_sensor_msgs::SerialData_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::asrl_sensor_msgs::SerialData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.stamp);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct SerialData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asrl_sensor_msgs::SerialData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::asrl_sensor_msgs::SerialData_<ContainerAllocator> & v) 
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // ASRL_SENSOR_MSGS_MESSAGE_SERIALDATA_H

